# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: xl

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'M.Sc. student in computer science'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Kai Helli"

# Site footer
footer:
  copyright:
    notice: '© {year} Kai Helli. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Mon, 02 Jan 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
